name: Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate coverage report
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: lcov.info
        fail_ci_if_error: true

    - name: Generate HTML coverage report
      run: cargo llvm-cov --all-features --workspace --html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/llvm-cov/html/

  test-coverage-threshold:
    name: Coverage Threshold Check
    runs-on: ubuntu-latest
    needs: coverage
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Check coverage threshold
      run: |
        coverage=$(cargo llvm-cov --all-features --workspace --summary-only | grep -E "Coverage: [0-9]+" | grep -oE "[0-9]+")
        echo "Current coverage: ${coverage}%"
        if [ "$coverage" -lt 90 ]; then
          echo "Coverage is below 90% threshold"
          exit 1
        fi
        echo "Coverage meets 90% threshold"